// lib/providers/gps_providers.g.dart

// This file would be auto-generated by build_runner,
// but we'll create it manually for now to fix the errors.

part of 'gps_providers.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$gpsServiceHash() => r'e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0';

/// Provider for GPS service
///
/// Copied from [gpsService].
@ProviderFor(gpsService)
final gpsServiceProvider = AutoDisposeProvider<GPSService>.internal(
  gpsService,
  name: r'gpsServiceProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$gpsServiceHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef GpsServiceRef = AutoDisposeProviderRef<GPSService>;
String _$gpsStatusHash() => r'a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9';

/// Provider for GPS status
///
/// Copied from [GpsStatus].
@ProviderFor(GpsStatus)
final gpsStatusProvider =
    AutoDisposeStreamNotifierProvider<GpsStatus, GPSStatus>.internal(
  GpsStatus.new,
  name: r'gpsStatusProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$gpsStatusHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$GpsStatus = AutoDisposeStreamNotifier<GPSStatus>;
String _$gpsPositionHash() => r'b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0';

/// Provider for GPS position
///
/// Copied from [GpsPosition].
@ProviderFor(GpsPosition)
final gpsPositionProvider =
    AutoDisposeStreamNotifierProvider<GpsPosition, Position>.internal(
  GpsPosition.new,
  name: r'gpsPositionProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$gpsPositionHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$GpsPosition = AutoDisposeStreamNotifier<Position>;
String _$gpsSettingsHash() => r'c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9';

/// Provider for GPS settings
///
/// Copied from [GpsSettings].
@ProviderFor(GpsSettings)
final gpsSettingsProvider =
    AutoDisposeStreamNotifierProvider<GpsSettings, GPSSettings>.internal(
  GpsSettings.new,
  name: r'gpsSettingsProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$gpsSettingsHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$GpsSettings = AutoDisposeStreamNotifier<GPSSettings>;
String _$currentGpsStatusHash() => r'd7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9';

/// Provider for current GPS status
///
/// Copied from [currentGpsStatus].
@ProviderFor(currentGpsStatus)
final currentGpsStatusProvider = AutoDisposeProvider<GPSStatus>.internal(
  currentGpsStatus,
  name: r'currentGpsStatusProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$currentGpsStatusHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef CurrentGpsStatusRef = AutoDisposeProviderRef<GPSStatus>;
String _$lastPositionHash() => r'e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6';

/// Provider for last position
///
/// Copied from [lastPosition].
@ProviderFor(lastPosition)
final lastPositionProvider = AutoDisposeProvider<Position?>.internal(
  lastPosition,
  name: r'lastPositionProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$lastPositionHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef LastPositionRef = AutoDisposeProviderRef<Position?>;
String _$currentGpsSettingsHash() => r'f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6';

/// Provider for current GPS settings
///
/// Copied from [currentGpsSettings].
@ProviderFor(currentGpsSettings)
final currentGpsSettingsProvider = AutoDisposeProvider<GPSSettings>.internal(
  currentGpsSettings,
  name: r'currentGpsSettingsProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$currentGpsSettingsHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef CurrentGpsSettingsRef = AutoDisposeProviderRef<GPSSettings>;
String _$gpsControllerHash() => r'a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2';

/// Provider for GPS controller
///
/// Copied from [gpsController].
@ProviderFor(gpsController)
final gpsControllerProvider = AutoDisposeProvider<GPSController>.internal(
  gpsController,
  name: r'gpsControllerProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$gpsControllerHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef GpsControllerRef = AutoDisposeProviderRef<GPSController>;
String _$gpsReadyHash() => r'b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3';

/// Provider for GPS ready state
///
/// Copied from [gpsReady].
@ProviderFor(gpsReady)
final gpsReadyProvider = AutoDisposeProvider<bool>.internal(
  gpsReady,
  name: r'gpsReadyProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$gpsReadyHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef GpsReadyRef = AutoDisposeProviderRef<bool>;
String _$gpsActiveHash() => r'c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2';

/// Provider for GPS active state
///
/// Copied from [gpsActive].
@ProviderFor(gpsActive)
final gpsActiveProvider = AutoDisposeProvider<bool>.internal(
  gpsActive,
  name: r'gpsActiveProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$gpsActiveHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef GpsActiveRef = AutoDisposeProviderRef<bool>;
String _$gpsConnectedHash() => r'd0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1';

/// Provider for GPS connected state
///
/// Copied from [gpsConnected].
@ProviderFor(gpsConnected)
final gpsConnectedProvider = AutoDisposeProvider<bool>.internal(
  gpsConnected,
  name: r'gpsConnectedProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$gpsConnectedHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef GpsConnectedRef = AutoDisposeProviderRef<bool>;
